version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: niot
      POSTGRES_DB: bms
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - bms_net

  webapp:
    image: bms-backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      DB_NAME: bms
    depends_on:
      - postgres
    networks:
      - bms_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -h postgres -p 5432 -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  bms_net:
    driver: bridge
